greeting: Hello

info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

management:
  security:
    enabled: false

---

spring:
  profiles: spanish

greeting: Hola